// All port codes are pure ASCII Latin — no Cyrillic characters
const ports = [
  // Asia
  { name: 'Shanghai', country: 'CN', code: 'CNSHA', region: 'Asia', baseRate: 35 },
  { name: 'Ningbo', country: 'CN', code: 'CNNGB', region: 'Asia', baseRate: 35 },
  { name: 'Shenzhen', country: 'CN', code: 'CNSZX', region: 'Asia', baseRate: 30 },
  { name: 'Guangzhou', country: 'CN', code: 'CNGUA', region: 'Asia', baseRate: 30 },
  { name: 'Qingdao', country: 'CN', code: 'CNTAO', region: 'Asia', baseRate: 40 },
  { name: 'Tianjin', country: 'CN', code: 'CNTSN', region: 'Asia', baseRate: 45 },
  { name: 'Hong Kong', country: 'HK', code: 'HKHKG', region: 'Asia', baseRate: 25 },
  { name: 'Singapore', country: 'SG', code: 'SGSIN', region: 'Asia', baseRate: 30 },
  { name: 'Busan', country: 'KR', code: 'KRPUS', region: 'Asia', baseRate: 35 },
  { name: 'Tokyo', country: 'JP', code: 'JPTYO', region: 'Asia', baseRate: 50 },
  { name: 'Yokohama', country: 'JP', code: 'JPYOK', region: 'Asia', baseRate: 50 },
  { name: 'Osaka', country: 'JP', code: 'JPOSA', region: 'Asia', baseRate: 50 },
  { name: 'Mumbai', country: 'IN', code: 'INBOM', region: 'Asia', baseRate: 45 },
  { name: 'Chennai', country: 'IN', code: 'INMAA', region: 'Asia', baseRate: 45 },
  { name: 'Nhava Sheva', country: 'IN', code: 'INNSA', region: 'Asia', baseRate: 40 },
  { name: 'Colombo', country: 'LK', code: 'LKCMB', region: 'Asia', baseRate: 40 },
  { name: 'Port Klang', country: 'MY', code: 'MYPKG', region: 'Asia', baseRate: 35 },
  { name: 'Penang', country: 'MY', code: 'MYPNG', region: 'Asia', baseRate: 35 },
  { name: 'Laem Chabang', country: 'TH', code: 'THLCH', region: 'Asia', baseRate: 40 },
  { name: 'Bangkok', country: 'TH', code: 'THBKK', region: 'Asia', baseRate: 40 },
  { name: 'Jakarta', country: 'ID', code: 'IDJKT', region: 'Asia', baseRate: 45 },
  { name: 'Surabaya', country: 'ID', code: 'IDSUB', region: 'Asia', baseRate: 45 },
  { name: 'Manila', country: 'PH', code: 'PHMNL', region: 'Asia', baseRate: 50 },
  { name: 'Cebu', country: 'PH', code: 'PHCEB', region: 'Asia', baseRate: 50 },
  { name: 'Kaohsiung', country: 'TW', code: 'TWKHH', region: 'Asia', baseRate: 35 },
  { name: 'Keelung', country: 'TW', code: 'TWKEL', region: 'Asia', baseRate: 35 },
  { name: 'Ho Chi Minh', country: 'VN', code: 'VNSGN', region: 'Asia', baseRate: 40 },
  { name: 'Haiphong', country: 'VN', code: 'VNHPH', region: 'Asia', baseRate: 40 },
  { name: 'Chittagong', country: 'BD', code: 'BDCGP', region: 'Asia', baseRate: 55 },
  { name: 'Karachi', country: 'PK', code: 'PKKAR', region: 'Asia', baseRate: 55 },
  { name: 'Yangon', country: 'MM', code: 'MMRGN', region: 'Asia', baseRate: 60 },
  // Middle East
  { name: 'Jebel Ali', country: 'AE', code: 'AEJEA', region: 'MiddleEast', baseRate: 45 },
  { name: 'Abu Dhabi', country: 'AE', code: 'AEAUH', region: 'MiddleEast', baseRate: 50 },
  { name: 'Sohar', country: 'OM', code: 'OMHOH', region: 'MiddleEast', baseRate: 55 },
  { name: 'Salalah', country: 'OM', code: 'OMSLL', region: 'MiddleEast', baseRate: 50 },
  { name: 'Jeddah', country: 'SA', code: 'SAJED', region: 'MiddleEast', baseRate: 50 },
  { name: 'Dammam', country: 'SA', code: 'SADMM', region: 'MiddleEast', baseRate: 55 },
  { name: 'Riyadh', country: 'SA', code: 'SARUH', region: 'MiddleEast', baseRate: 65 },
  { name: 'Aqaba', country: 'JO', code: 'JOAQJ', region: 'MiddleEast', baseRate: 60 },
  { name: 'Kuwait', country: 'KW', code: 'KWKWI', region: 'MiddleEast', baseRate: 65 },
  { name: 'Bahrain', country: 'BH', code: 'BHBAH', region: 'MiddleEast', baseRate: 65 },
  { name: 'Doha', country: 'QA', code: 'QADOH', region: 'MiddleEast', baseRate: 65 },
  { name: 'Bandar Abbas', country: 'IR', code: 'IRBND', region: 'MiddleEast', baseRate: 70 },
  // Europe
  { name: 'Rotterdam', country: 'NL', code: 'NLRTM', region: 'Europe', baseRate: 35 },
  { name: 'Antwerp', country: 'BE', code: 'BEANR', region: 'Europe', baseRate: 35 },
  { name: 'Hamburg', country: 'DE', code: 'DEHAM', region: 'Europe', baseRate: 40 },
  { name: 'Bremerhaven', country: 'DE', code: 'DEBRV', region: 'Europe', baseRate: 40 },
  { name: 'Felixstowe', country: 'GB', code: 'GBFXT', region: 'Europe', baseRate: 45 },
  { name: 'Southampton', country: 'GB', code: 'GBSOU', region: 'Europe', baseRate: 45 },
  { name: 'London', country: 'GB', code: 'GBLON', region: 'Europe', baseRate: 50 },
  { name: 'Le Havre', country: 'FR', code: 'FRLEH', region: 'Europe', baseRate: 45 },
  { name: 'Marseille', country: 'FR', code: 'FRMRS', region: 'Europe', baseRate: 50 },
  { name: 'Barcelona', country: 'ES', code: 'ESBCN', region: 'Europe', baseRate: 45 },
  { name: 'Valencia', country: 'ES', code: 'ESVLC', region: 'Europe', baseRate: 45 },
  { name: 'Algeciras', country: 'ES', code: 'ESALG', region: 'Europe', baseRate: 40 },
  { name: 'Piraeus', country: 'GR', code: 'GRPIR', region: 'Europe', baseRate: 50 },
  { name: 'Thessaloniki', country: 'GR', code: 'GRSKG', region: 'Europe', baseRate: 55 },
  { name: 'Istanbul', country: 'TR', code: 'TRIST', region: 'Europe', baseRate: 55 },
  { name: 'Mersin', country: 'TR', code: 'TRMER', region: 'Europe', baseRate: 60 },
  { name: 'Izmir', country: 'TR', code: 'TRIZM', region: 'Europe', baseRate: 60 },
  { name: 'Gemlik', country: 'TR', code: 'TRGEM', region: 'Europe', baseRate: 60 },
  { name: 'Derince', country: 'TR', code: 'TRDER', region: 'Europe', baseRate: 60 },
  { name: 'Ambarli', country: 'TR', code: 'TRAMB', region: 'Europe', baseRate: 55 },
  { name: 'Trieste', country: 'IT', code: 'ITTRS', region: 'Europe', baseRate: 55 },
  { name: 'Genoa', country: 'IT', code: 'ITGOA', region: 'Europe', baseRate: 50 },
  { name: 'Gioia Tauro', country: 'IT', code: 'ITGIT', region: 'Europe', baseRate: 50 },
  { name: 'Venice', country: 'IT', code: 'ITVCE', region: 'Europe', baseRate: 55 },
  { name: 'Livorno', country: 'IT', code: 'ITLIV', region: 'Europe', baseRate: 55 },
  { name: 'Dunkirk', country: 'FR', code: 'FRDKK', region: 'Europe', baseRate: 50 },
  { name: 'Gdansk', country: 'PL', code: 'PLGDN', region: 'Europe', baseRate: 65 },
  { name: 'Gdynia', country: 'PL', code: 'PLGDY', region: 'Europe', baseRate: 65 },
  { name: 'Constanta', country: 'RO', code: 'ROCSN', region: 'Europe', baseRate: 65 },
  { name: 'Koper', country: 'SI', code: 'SIKOP', region: 'Europe', baseRate: 60 },
  { name: 'Zeebrugge', country: 'BE', code: 'BEZEE', region: 'Europe', baseRate: 40 },
  { name: 'Gothenburg', country: 'SE', code: 'SEGOT', region: 'Europe', baseRate: 55 },
  { name: 'Oslo', country: 'NO', code: 'NOOSL', region: 'Europe', baseRate: 60 },
  { name: 'Copenhagen', country: 'DK', code: 'DKCPH', region: 'Europe', baseRate: 55 },
  { name: 'Helsinki', country: 'FI', code: 'FIHEL', region: 'Europe', baseRate: 65 },
  { name: 'Tallinn', country: 'EE', code: 'EETLL', region: 'Europe', baseRate: 70 },
  { name: 'Riga', country: 'LV', code: 'LVRIX', region: 'Europe', baseRate: 70 },
  { name: 'Klaipeda', country: 'LT', code: 'LTKLJ', region: 'Europe', baseRate: 70 },
  { name: 'Lisbon', country: 'PT', code: 'PTLIS', region: 'Europe', baseRate: 55 },
  { name: 'Porto', country: 'PT', code: 'PTOPO', region: 'Europe', baseRate: 55 },
  { name: 'Malta', country: 'MT', code: 'MTMLA', region: 'Europe', baseRate: 60 },
  { name: 'Limassol', country: 'CY', code: 'CYLMS', region: 'Europe', baseRate: 60 },
  // Americas
  { name: 'New York', country: 'US', code: 'USNYC', region: 'Americas', baseRate: 60 },
  { name: 'Los Angeles', country: 'US', code: 'USLAX', region: 'Americas', baseRate: 50 },
  { name: 'Long Beach', country: 'US', code: 'USLGB', region: 'Americas', baseRate: 50 },
  { name: 'Houston', country: 'US', code: 'USHOU', region: 'Americas', baseRate: 65 },
  { name: 'Savannah', country: 'US', code: 'USSAV', region: 'Americas', baseRate: 60 },
  { name: 'Miami', country: 'US', code: 'USMIA', region: 'Americas', baseRate: 60 },
  { name: 'Seattle', country: 'US', code: 'USSEA', region: 'Americas', baseRate: 55 },
  { name: 'Tacoma', country: 'US', code: 'USTCM', region: 'Americas', baseRate: 55 },
  { name: 'Baltimore', country: 'US', code: 'USBLT', region: 'Americas', baseRate: 65 },
  { name: 'Norfolk', country: 'US', code: 'USORF', region: 'Americas', baseRate: 65 },
  { name: 'Charleston', country: 'US', code: 'USCHS', region: 'Americas', baseRate: 60 },
  { name: 'New Orleans', country: 'US', code: 'USMSY', region: 'Americas', baseRate: 70 },
  { name: 'Vancouver', country: 'CA', code: 'CAVAN', region: 'Americas', baseRate: 60 },
  { name: 'Montreal', country: 'CA', code: 'CAMTR', region: 'Americas', baseRate: 70 },
  { name: 'Halifax', country: 'CA', code: 'CAHAL', region: 'Americas', baseRate: 70 },
  { name: 'Manzanillo', country: 'MX', code: 'MXZLO', region: 'Americas', baseRate: 65 },
  { name: 'Veracruz', country: 'MX', code: 'MXVER', region: 'Americas', baseRate: 70 },
  { name: 'Lazaro Cardenas', country: 'MX', code: 'MXLZC', region: 'Americas', baseRate: 65 },
  { name: 'Cartagena', country: 'CO', code: 'COCLO', region: 'Americas', baseRate: 75 },
  { name: 'Buenaventura', country: 'CO', code: 'COBUN', region: 'Americas', baseRate: 75 },
  { name: 'Santos', country: 'BR', code: 'BRSSZ', region: 'Americas', baseRate: 80 },
  { name: 'Rio de Janeiro', country: 'BR', code: 'BRRIO', region: 'Americas', baseRate: 85 },
  { name: 'Buenos Aires', country: 'AR', code: 'ARBUE', region: 'Americas', baseRate: 90 },
  { name: 'Montevideo', country: 'UY', code: 'UYMVD', region: 'Americas', baseRate: 85 },
  { name: 'Callao', country: 'PE', code: 'PELIM', region: 'Americas', baseRate: 80 },
  { name: 'Guayaquil', country: 'EC', code: 'ECGYE', region: 'Americas', baseRate: 80 },
  { name: 'Panama City', country: 'PA', code: 'PAPTY', region: 'Americas', baseRate: 70 },
  { name: 'Colon', country: 'PA', code: 'PACON', region: 'Americas', baseRate: 70 },
  { name: 'Kingston', country: 'JM', code: 'JMKIN', region: 'Americas', baseRate: 75 },
  { name: 'Puerto Rico', country: 'US', code: 'USSJP', region: 'Americas', baseRate: 75 },
  // Africa
  { name: 'Durban', country: 'ZA', code: 'ZADUR', region: 'Africa', baseRate: 80 },
  { name: 'Cape Town', country: 'ZA', code: 'ZACPT', region: 'Africa', baseRate: 85 },
  { name: 'Port Elizabeth', country: 'ZA', code: 'ZAELS', region: 'Africa', baseRate: 85 },
  { name: 'Richards Bay', country: 'ZA', code: 'ZARCS', region: 'Africa', baseRate: 90 },
  { name: 'Mombasa', country: 'KE', code: 'KEMBA', region: 'Africa', baseRate: 95 },
  { name: 'Dar es Salaam', country: 'TZ', code: 'TZDAR', region: 'Africa', baseRate: 95 },
  { name: 'Djibouti', country: 'DJ', code: 'DJJIB', region: 'Africa', baseRate: 90 },
  { name: 'Berbera', country: 'SO', code: 'SOBBO', region: 'Africa', baseRate: 100 },
  { name: 'Alexandria', country: 'EG', code: 'EGALY', region: 'Africa', baseRate: 65 },
  { name: 'Port Said', country: 'EG', code: 'EGPSD', region: 'Africa', baseRate: 65 },
  { name: 'Dakar', country: 'SN', code: 'SNDKR', region: 'Africa', baseRate: 85 },
  { name: 'Lagos', country: 'NG', code: 'NGLOS', region: 'Africa', baseRate: 100 },
  { name: 'Tema', country: 'GH', code: 'GHTEM', region: 'Africa', baseRate: 95 },
  { name: 'Abidjan', country: 'CI', code: 'CIABJ', region: 'Africa', baseRate: 95 },
  { name: 'Douala', country: 'CM', code: 'CMDLA', region: 'Africa', baseRate: 110 },
  { name: 'Luanda', country: 'AO', code: 'AOUAN', region: 'Africa', baseRate: 120 },
  { name: 'Maputo', country: 'MZ', code: 'MZMPM', region: 'Africa', baseRate: 100 },
  { name: 'Beira', country: 'MZ', code: 'MZBEW', region: 'Africa', baseRate: 105 },
  { name: 'Toamasina', country: 'MG', code: 'MGTMM', region: 'Africa', baseRate: 115 },
  { name: 'Casablanca', country: 'MA', code: 'MACAS', region: 'Africa', baseRate: 70 },
  { name: 'Tangier', country: 'MA', code: 'MATAN', region: 'Africa', baseRate: 65 },
  { name: 'Tunis', country: 'TN', code: 'TNTUN', region: 'Africa', baseRate: 75 },
  { name: 'Tripoli', country: 'LY', code: 'LYTIP', region: 'Africa', baseRate: 85 },
  // Oceania
  { name: 'Sydney', country: 'AU', code: 'AUSYD', region: 'Oceania', baseRate: 75 },
  { name: 'Melbourne', country: 'AU', code: 'AUMEL', region: 'Oceania', baseRate: 75 },
  { name: 'Brisbane', country: 'AU', code: 'AUBNE', region: 'Oceania', baseRate: 80 },
  { name: 'Fremantle', country: 'AU', code: 'AUFRE', region: 'Oceania', baseRate: 80 },
  { name: 'Adelaide', country: 'AU', code: 'AUADL', region: 'Oceania', baseRate: 85 },
  { name: 'Darwin', country: 'AU', code: 'AUDRW', region: 'Oceania', baseRate: 95 },
  { name: 'Auckland', country: 'NZ', code: 'NZAKL', region: 'Oceania', baseRate: 85 },
  { name: 'Wellington', country: 'NZ', code: 'NZWLG', region: 'Oceania', baseRate: 90 },
  { name: 'Lyttelton', country: 'NZ', code: 'NZLYT', region: 'Oceania', baseRate: 90 },
  { name: 'Port Moresby', country: 'PG', code: 'PGPOM', region: 'Oceania', baseRate: 110 },
  { name: 'Suva', country: 'FJ', code: 'FJSUV', region: 'Oceania', baseRate: 120 },
  { name: 'Noumea', country: 'NC', code: 'NCNOU', region: 'Oceania', baseRate: 120 }
];

module.exports = ports;
